### ISSUE TITLE
Markwon inside RecyclerView doesn't load images on certain conditions

### ISSUE THREAD

**Issue by Adonai** [noties/Markwon#120]
* **Markwon version**: 3.0.1

Expected: Markwon should load all images correctly.
Actual: Markwon sometimes skips image loading on scrolling.

The issue manifests itself in following conditions:
1. Have a RecyclerView with lots of items
2. Have TextView with markdown content and images in all of them
3. Wait for first image to get loaded

It's quite weird bug, but I noticed that when first item image gets loaded, the second RecyclerView item gets hidden below the bottom, i.e. it's not visible anymore as first item is now expanded because of image.

Then RecyclerView tries to hide it. Reasonable, because it's not visible anymore, right? Unfortunately this stops async drawable loading and never restarts it again.

Carefully set up conditional breakpoints network gave me this stacktrace, so you can see why it happens:

```
	  at java.lang.Thread.interrupt(Thread.java:949)
	  at java.util.concurrent.FutureTask.cancel(FutureTask.java:146)
	  at ru.noties.markwon.image.AsyncDrawableLoaderImpl.cancel(AsyncDrawableLoaderImpl.java:51)
	  at ru.noties.markwon.image.AsyncDrawable.setCallback2(AsyncDrawable.java:94)
	  at ru.noties.markwon.image.AsyncDrawableScheduler.unschedule(AsyncDrawableScheduler.java:53)
	  at ru.noties.markwon.image.AsyncDrawableScheduler$1.onViewDetachedFromWindow(AsyncDrawableScheduler.java:35)
	  at android.view.View.dispatchDetachedFromWindow(View.java:15463)
	  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
	  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3216)
	  at android.view.ViewGroup.removeDetachedView(ViewGroup.java:5006)
	  at androidx.recyclerview.widget.RecyclerView.removeDetachedView(RecyclerView.java:4206)
	  at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:9066)
	  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4063)
	  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3718)
	  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260)
	  at android.view.View.layout(View.java:17523)
```

So the image loading gets interrupted. 
The obvious fix for me seems to be in adding `schedule(textView)` into `AsyncDrawableScheduler -> schedule -> listener -> onViewAttachedToWindow`.

For now I workaround this by adding another `OnAttachStateChangeListener` to my text view with `AsyncDrawableScheduler.schedule(label)`.

**Comment by noties** [comment]
Hello @Adonai !

This is an interesting problem. As you correctly noticed AsyncDrawableScheduler adds an `OnAttachStateChangedListener` for all `AsyncDrawableSpan`s. This is done to cancel ongoing requests when a TextView is no longer attached to a window. And this works good when TextView is in a _regular_ layout. Things change when a TextView is in RecyclerView. Because RecyclerView _recycles_ views, so they go through `attach/detach` events multiple times. And `AsyncDrawableScheduler` listens for `detach` events to release span from referencing by removing callbacks (in order to prevent memory leaks), but do not listen for subsequent `attach` events. So, once a TextView is _recycled_ (aka detached) it won't be able to invalidate an `AsyncDrawableSpan`, even if it would be attached again at some point in future.

As a work-around, `AsyncDrawableScheduler` indeed can listen for subsequent `attach` events. I think it's relatively safe to do so (not 100% sure though, I think we better run some tests to validate that this won't cause memory leaks or break current implementation).

Also, are you using [recycler](https://github.com/noties/Markwon/tree/master/markwon-recycler) artifact? It short -&gt; it splits resulting Document into independent nodes and renders each in an individual TextView. As it applies markdown on each `onBindViewHolder`, image loading is still triggered. It still cancels loading when a TextView is detached, but at least resumes the loading when TextView becomes attached again. I'm not saying you should jump into using this artifact, but maybe inspect it for implementation details that could help you with your use-case. There is also a simple [sample application](https://github.com/noties/Markwon/blob/master/sample/src/main/java/ru/noties/markwon/sample/recycler/RecyclerActivity.java) if you wish to know how to use it. And do not forget the [documentation](https://noties.io/Markwon/docs/v3/recycler/) that also has some explanations.

**Comment by Adonai** [comment]
No, I'm not using recycler. I'll give it a try, I think, but in my application there are "spoiler" spans which unwrap more text (and spans) on click and I'm not sure multi-textview recycler can handle this.

I should say that workaround with scheduling on attach works pretty well for my purposes. I'll post here if I find any bugs.

**Comment by noties** [comment]
I'm going to close it now, but feel free to reopen it if you find anything else
