### ISSUE TITLE
MARKWON-IMAGE: Error loading image:(image url) Exception obtaining network resource:(image url) 

### ISSUE THREAD

**Issue by xiaoyvyv** [noties/Markwon#194]
**Markwon version**:4.2.1

**Unable to load network picture resource，It happens all the time。**

**Here is the markdown text**

```html
<center>
<img src="http://img.xiaoyv.top/bbs/201603246-20aa1b8ad8bf27df3c906473619c2d84.jpg" width="98%" height="auto">
<br><strong>自定义图片标题</strong><br><br>
</center>
```

**lmage url：http://img.xiaoyv.top/bbs/201603246-20aa1b8ad8bf27df3c906473619c2d84.jpg  ，It will be redirected to another domain name：http://cdn.xiaoyv.top/xxxx**

**Here is the java code**

```java
       markwon = Markwon.builder(activity)
                .usePlugin(JLatexMathPlugin.create(ConvertUtils.dp2px(18)))
                .usePlugin(SyntaxHighlightPlugin.create(prism4j, prism4JThemeDarkula))
                .usePlugin(TablePlugin.create(activity))
                .usePlugin(TaskListPlugin.create(activity))
                .usePlugin(StrikethroughPlugin.create())
                .usePlugin(HtmlPlugin.create().addHandler(new CenterTagHandler()))
                .usePlugin(ImagesPlugin.create(plugin -> {
                    plugin.addSchemeHandler(FileSchemeHandler.create());
                    plugin.addSchemeHandler(DataUriSchemeHandler.create());
                    plugin.addSchemeHandler(OkHttpNetworkSchemeHandler.create());
                }))
                .build();
```

**After using `OkHttpNetworkSchemeHandler`, the following is the error message:**

```java
    E/MARKWON-IMAGE: Error loading image: http://img.xiaoyv.top/bbs/201603246-20aa1b8ad8bf27df3c906473619c2d84.jpg
    java.lang.IllegalStateException: Exception obtaining network resource: http://img.xiaoyv.top/bbs/201603246-20aa1b8ad8bf27df3c906473619c2d84.jpg
        at io.noties.markwon.image.network.OkHttpNetworkSchemeHandler.handle(OkHttpNetworkSchemeHandler.java:68)
        at io.noties.markwon.image.AsyncDrawableLoaderImpl$1.run(AsyncDrawableLoaderImpl.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.InterruptedIOException: thread interrupted
        at okio.Timeout.throwIfReached(Timeout.java:145)
        at okio.Okio$1.write(Okio.java:76)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
        at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
        at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
```

**After not using `OkHttpNetworkSchemeHandler`, the following is the warning message:**

```java
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:790)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:765)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:806)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at io.noties.markwon.image.DefaultMediaDecoder.decode(DefaultMediaDecoder.java:48)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at io.noties.markwon.image.AsyncDrawableLoaderImpl$1.run(AsyncDrawableLoaderImpl.java:123)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu D/skia: ---- read threw an exception
2020-02-14 20:16:23.556 12778-13366/com.yangtzeu D/skia: libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
```
* **And the `TextView`  show only one character(OBJ)**

**Comment by noties** [comment]
@xiaoyvyv please fill the placeholders of the issue body

**Comment by xiaoyvyv** [comment]
The error is because the picture link will be redirected to another domain?

**Comment by xiaoyvyv** [comment]
My network environment is OK, and the glide can load pictures smoothly

**Comment by xiaoyvyv** [comment]
This error also occurs when using `GlideImagesPlugin`

**Comment by noties** [comment]
This image works for me. 

* How are you applying your markdown?
* Where markdown is displayed? In a TextView, EditText, TextView inside a RecyclerView, other?

**Comment by xiaoyvyv** [comment]
> This image works for me.
> 
> * How are you applying your markdown?
> * Where markdown is displayed? In a TextView, EditText, TextView inside a RecyclerView, other?

```java

        private AppCompatTextView flarumContent;
        ...

        flarumContent = findViewById(R.id.flarum_topic_content);
        ...

        markwon = Markwon.builder(activity)
                .usePlugin(JLatexMathPlugin.create(ConvertUtils.dp2px(18)))
                .usePlugin(SyntaxHighlightPlugin.create(prism4j, prism4JThemeDarkula))
                .usePlugin(TablePlugin.create(activity))
                .usePlugin(TaskListPlugin.create(activity))
                .usePlugin(StrikethroughPlugin.create())
                .usePlugin(HtmlPlugin.create().addHandler(new CenterTagHandler()))
                .usePlugin(ImagesPlugin.create(plugin -> {
                    plugin.addSchemeHandler(FileSchemeHandler.create());
                    plugin.addSchemeHandler(DataUriSchemeHandler.create());
                    plugin.addSchemeHandler(OkHttpNetworkSchemeHandler.create());
                }))
                .build();
        

        // 显示 MarkDown内容
        String markText="<center>\n" +
                "<img src=\"http://img.xiaoyv.top/bbs/201603246-20aa1b8ad8bf27df3c906473619c2d84.jpg\" width=\"98%\" height=\"auto\">\n" +
                "<br><strong>自定义图片标题</strong><br><br>\n" +
                "</center>";
        
        markwon.setMarkdown(flarumContent,markText);
```
#### Layout xml
```xml
<androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/flarum_topic_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?attr/colorLayout"
            android:breakStrategy="simple"
            android:hyphenationFrequency="none"
            android:lineSpacingExtra="5dp"
            android:padding="10dp"
            android:text="这里是话题内容"
            android:textSize="14sp"
            tools:targetApi="m" />
```

**Comment by noties** [comment]
Can you try with redirects explicitly enabled?

```java
final OkHttpClient client = new OkHttpClient.Builder()
        .followRedirects(true)
        .followSslRedirects(true)
        .build();
plugin.addSchemeHandler(OkHttpNetworkSchemeHandler.create(client));
```

You should also know that starting with API 28 non secure (HTTP) network requests are disabled by default and require explicit network config to be enabled

**Comment by noties** [comment]
Feel free to reopen if issue is not solved
