### ISSUE TITLE
Canvas trying to draw too large bitmap

### ISSUE THREAD

**Issue by zend10** [noties/Markwon#280]
* **Markwon version**: 4.4.0

First of all, it's working well, but it seems there's a problem with huge image. Not sure if I'm configuring it wrongly. Correct me if I'm wrong please.

This is how I configure the builder. I've made sure to use Glide plugin.
```
val markwon = Markwon.builder(context)
            .usePlugin(GlideImagesPlugin.create(GlideApp.with(context)))
            .usePlugin(ImagesPlugin.create(ImagesPlugin.ImagesConfigure {
                it.addMediaDecoder(GifMediaDecoder.create(true))
            }))
            .usePlugin(StrikethroughPlugin.create())
            .usePlugin(SoftBreakAddsNewLinePlugin.create())
            .usePlugin(object : AbstractMarkwonPlugin() {
                override fun configureTheme(builder: MarkwonTheme.Builder) {
                    builder.headingBreakHeight(0)
                }
                override fun configure(registry: MarkwonPlugin.Registry) {
                    registry.require(HtmlPlugin::class.java) {
                        it.addHandler(AlignTagHandler())
                    }
                }
            })
            .usePlugin(HtmlPlugin.create())
            .build()

val node = markwon.parse(markdownString)
val markdown = markwon.render(node)
markwon.setParsedMarkdown(textView, markdown)
```

But this is the result. I don't have the image and can't provide the image but, yes, `129762720bytes` is what I got from crashlytics.
```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(129762720bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
       at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
       at io.noties.markwon.image.AsyncDrawable.draw(AsyncDrawable.java:310)
       at io.noties.markwon.image.AsyncDrawableSpan.draw(AsyncDrawableSpan.java:126)
       at android.text.TextLine.handleReplacement(TextLine.java:949)
       at android.text.TextLine.handleRun(TextLine.java:1049)
       at android.text.TextLine.drawRun(TextLine.java:484)
       at android.text.TextLine.draw(TextLine.java:217)
       at android.text.Layout.drawText(Layout.java:545)
       at android.widget.Editor.drawHardwareAcceleratedInner(Editor.java:1933)
       at android.widget.Editor.drawHardwareAccelerated(Editor.java:1849)
       at android.widget.Editor.onDraw(Editor.java:1789)
       at android.widget.TextView.onDraw(TextView.java:7779)
       at android.view.View.draw(View.java:20373)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20376)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20376)
       at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1931)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20376)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20376)
       at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19309)
       at android.view.View.draw(View.java:20096)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20376)
       at com.android.internal.policy.DecorView.draw(DecorView.java:980)
       at android.view.View.updateDisplayListIfDirty(View.java:19318)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3501)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3288)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Please tell me if I'm doing something wrong.

**Comment by noties** [comment]
Hello @zend10 ,

is it possible that you are loading a local resource (bundled with your app)? If so you might want to look at this [stackoverflow thread](https://stackoverflow.com/questions/40835514/android-canvas-drawing-too-large-bitmap) for a reference

**Comment by zend10** [comment]
Sorry that I forgot to specify that the whole markdown, including the image, was retrieved from an API.

**Comment by noties** [comment]
@zend10 129 megabytes is a big image. And although it is the size of _raw_ uncompressed image, it is still very big (for example ~`30_000 x 4000` pixels). Unfortunately `markwon-image` cannot handle such images as it tries to load them in memory and does not process them in any way. I think you have better chance with one of other image loaders that we have:

* [markwon-coil](https://noties.io/Markwon/docs/v4/image-coil/)
* [markwon-glide](https://noties.io/Markwon/docs/v4/image-glide/)
* [markwon-picasso](https://noties.io/Markwon/docs/v4/image-picasso/)

Please note that you must additionally resize image if it exceeds some maximum (for example `onlyScaleDown` in Picasso etc)

**Comment by zend10** [comment]
Is using both `markwon-image` and `markwon-glide` like this valid? I need to the `glide`, but still support gif at the same time.

```
Markwon.builder(context)
            .usePlugin(GlideImagesPlugin.create(GlideApp.with(context)))
            .usePlugin(ImagesPlugin.create(ImagesPlugin.ImagesConfigure {
                it.addMediaDecoder(GifMediaDecoder.create(true))
            }))
            .build()
```

**Comment by noties** [comment]
No @zend10 , unfortunately it is not valid, only one image loader can be used

**Comment by zend10** [comment]
I see. I guess I'll have to drop support for gif images.

Thank you for your

**Comment by noties** [comment]
Hello @zend10 ,

Glide does support GIF out of box: [sample](https://noties.io/Markwon/app/sample/20200820071942)

**Comment by zend10** [comment]
Oh lovely. Thank you for that. That's very helpful.
