### ISSUE TITLE
Problems showing live preview

### ISSUE THREAD

**Issue by MFlisar** [noties/Markwon#290]
## Infos

* **Markwon version**: 4.5.1

## Please specify expected/actual behavior

I do get exceptions as soon as I add html tag support to my app. It's a simple editor which shows an immediate preview on every text change. Setup looks like following:

```
val markwon = Markwon.builder(requireContext())
	.usePlugins(
		listOf(
			TaskListPlugin.create(requireContext()),
			TablePlugin.create(requireContext()),
			StrikethroughPlugin.create(),
			HtmlPlugin.create()
				.allowNonClosedTags(true),
			CoilImagesPlugin.create(
				requireContext(),
				ImageLoader.Builder(requireContext())
					.availableMemoryPercentage(0.5)
					.bitmapPoolPercentage(0.5)
					.crossfade(true)
					.build()
			)
		)
	)
	.textSetter(PrecomputedTextSetterCompat.create(Executors.newCachedThreadPool()))
	.build()
val editor = MarkwonEditor.create(markwon)
val textWatcher = MarkwonEditorTextWatcher.withPreRender(
	editor,
	Executors.newCachedThreadPool(),
	binding.etRaw
)

binding.etRaw.addTextChangedListener(textWatcher)
binding.etRaw.addTextChangedListener(SimpleTextWatcher {
	markwon.setMarkdown(binding.tvFormatted, it)
})
```

The user does input some text inside `binding.etRaw` and this is immediately rendered inside `binding.tvFormatted`. Without the html plugin I could not see any problems yet but with it I do see crashes (either of following 2):

**Stacktrace 1**

```
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2$2.run(MarkwonEditorTextWatcher.java:168)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at java.util.ArrayList.get(ArrayList.java:439)
	at io.noties.markwon.html.MarkwonHtmlParserImpl.findOpenInlineTag(MarkwonHtmlParserImpl.java:395)
	at io.noties.markwon.html.MarkwonHtmlParserImpl.processInlineTagEnd(MarkwonHtmlParserImpl.java:265)
	at io.noties.markwon.html.MarkwonHtmlParserImpl.processFragment(MarkwonHtmlParserImpl.java:168)
	at io.noties.markwon.html.HtmlPlugin.visitHtml(HtmlPlugin.java:177)
	at io.noties.markwon.html.HtmlPlugin.access$000(HtmlPlugin.java:28)
	at io.noties.markwon.html.HtmlPlugin$1.visit(HtmlPlugin.java:170)
	at io.noties.markwon.html.HtmlPlugin$1.visit(HtmlPlugin.java:167)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:183)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:111)
	at org.commonmark.node.HtmlInline.accept(HtmlInline.java:14)
	at io.noties.markwon.MarkwonVisitorImpl.visitChildren(MarkwonVisitorImpl.java:214)
	at io.noties.markwon.core.CorePlugin$14.visit(CorePlugin.java:507)
	at io.noties.markwon.core.CorePlugin$14.visit(CorePlugin.java:496)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:183)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:146)
	at org.commonmark.node.Paragraph.accept(Paragraph.java:7)
	at io.noties.markwon.MarkwonVisitorImpl.visitChildren(MarkwonVisitorImpl.java:214)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:185)
	at io.noties.markwon.MarkwonVisitorImpl.visit(MarkwonVisitorImpl.java:81)
	at org.commonmark.node.Document.accept(Document.java:7)
	at io.noties.markwon.MarkwonImpl.render(MarkwonImpl.java:77)
	at io.noties.markwon.MarkwonImpl.toMarkdown(MarkwonImpl.java:97)
	at io.noties.markwon.editor.MarkwonEditorImpl.process(MarkwonEditorImpl.java:45)
	at io.noties.markwon.editor.MarkwonEditorImpl.preRender(MarkwonEditorImpl.java:157)
	at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2.run(MarkwonEditorTextWatcher.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Stacktrace 2**

```
java.lang.RuntimeException: java.util.ConcurrentModificationException
        at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2$2.run(MarkwonEditorTextWatcher.java:168)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:866)
        at io.noties.markwon.html.MarkwonHtmlParserImpl.flushInlineTags(MarkwonHtmlParserImpl.java:191)
        at io.noties.markwon.html.MarkwonHtmlRendererImpl.render(MarkwonHtmlRendererImpl.java:36)
        at io.noties.markwon.html.HtmlPlugin.afterRender(HtmlPlugin.java:152)
        at io.noties.markwon.MarkwonImpl.render(MarkwonImpl.java:80)
        at io.noties.markwon.MarkwonImpl.toMarkdown(MarkwonImpl.java:97)
        at io.noties.markwon.editor.MarkwonEditorImpl.process(MarkwonEditorImpl.java:45)
        at io.noties.markwon.editor.MarkwonEditorImpl.preRender(MarkwonEditorImpl.java:157)
        at io.noties.markwon.editor.MarkwonEditorTextWatcher$WithPreRender$2.run(MarkwonEditorTextWatcher.java:137)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

## Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

All I need to do is to insert type following inside my `EditText`:

> <sub>

And it already crashes. If I do **not** use following

```
binding.etRaw.addTextChangedListener(SimpleTextWatcher {
	markwon.setMarkdown(binding.tvFormatted, it)
})
```

everything works.

*Is there a better way to implement the live preview during typing?*

## Custom classes

I use a class that I call `SimpleTextWatcher`, it just implements most `TextWatcher` functions as empty functions and only uses one of the 3 for easier and shorter usage. It simply looks like this:

```
class SimpleTextWatcher(
    val onChange: (String) -> Unit
) : TextWatcher {
    override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
    }

    override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
    }

    override fun afterTextChanged(p0: Editable?) {
        onChange(p0?.toString() ?: "")
    }
}
```

**Comment by noties** [comment]
Hello @MFlisar ,

I think you have a crash because you are reusing the `markwon` instance between multiple threads - one is parsing input and the same one is rendering results (thanks for 2 stacktraces that you'd provided - the second one gave me the hint). Unfortunately HTML parser is currently stateful and reused between multiple calls. To fix this issue - use two separate `Markwon` instances. Meanwhile let me think how can we make HTML parser stateless at least between multiple parsing stages

**Comment by MFlisar** [comment]
I just got up and while driving to my work I thought exactly the same (before I read your reply). And I tested it now and it seems to work so far, thank you very much.
