### ISSUE TITLE
Getting error trying to add simple-ext with existing delimiter

### ISSUE THREAD

**Issue by Shunaylov** [noties/Markwon#311]
* **Markwon version**: v4.6.0

I have a code, I want StrongEmphasis to work with one '*' instead of two. I added simple-ext plugins like this: 
`
    return Markwon.builder(context)
            .usePlugin(SoftBreakAddsNewLinePlugin.create()) 
            .textSetter(PrecomputedTextSetterCompat.create(Executors.newCachedThreadPool()))
            .usePlugin(LinkifyPlugin.create(Linkify.WEB_URLS))
            .usePlugin(MovementMethodPlugin.link())
            .usePlugin(SimpleExtPlugin.create { plugin ->
                plugin.addExtension(1, '~') { _, _ ->
                    StrikethroughSpan()
                }
            })
            .usePlugin(SimpleExtPlugin.create { plugin ->
                plugin.addExtension(1, '*') { _, _ ->
                    StrongEmphasisSpan()
                }
            })
            .usePlugin(SimpleExtPlugin.create { plugin ->
                plugin.addExtension(1, '_') { _, _ ->
                    EmphasisSpan()
                }
            }).build()
`

But after running it I had an error: 
`
java.lang.IllegalArgumentException: Cannot add two delimiter processors for char '*' and minimum length 1
        at org.commonmark.internal.StaggeredDelimiterProcessor.add(StaggeredDelimiterProcessor.java:55)
        at org.commonmark.internal.InlineParserImpl.addDelimiterProcessors(InlineParserImpl.java:125)
        at org.commonmark.internal.InlineParserImpl.calculateDelimiterProcessors(InlineParserImpl.java:107)
        at org.commonmark.internal.InlineParserImpl.<init>(InlineParserImpl.java:75)
        at org.commonmark.parser.Parser$Builder$1.create(Parser.java:256)
        at org.commonmark.parser.Parser.<init>(Parser.java:43)
        at org.commonmark.parser.Parser.<init>(Parser.java:28)
        at org.commonmark.parser.Parser$Builder.build(Parser.java:126)
        at io.noties.markwon.MarkwonBuilderImpl.build(MarkwonBuilderImpl.java:124)
`

So here is the question: 
How can I override an existing delimiter that does Core contain?

**Comment by noties** [comment]
Hello @Shunaylov ,

there is an experimental [inline-parser](https://noties.io/Markwon/docs/v4/inline-parser/) plugin that allows modifying core parsing features. There are also some [samples](https://noties.io/Markwon/app/search?a=inline-parser) available

**Comment by Shunaylov** [comment]
Used this: https://noties.io/Markwon/docs/v4/inline-parser/
works great
