### ISSUE TITLE
ImageSizeResolverDef crash NullPointerException

### ISSUE THREAD

**Issue by huweijian5** [noties/Markwon#321]
* **Markwon version**: 4.6.0

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
	at io.noties.markwon.image.ImageSizeResolverDef.resolveImageSize(ImageSizeResolverDef.java:23)
	at io.noties.markwon.image.AsyncDrawable.resolveBounds(AsyncDrawable.java:383)
	at io.noties.markwon.image.AsyncDrawable.initBounds(AsyncDrawable.java:278)
	at io.noties.markwon.image.AsyncDrawable.initWithKnownDimensions(AsyncDrawable.java:319)
	at io.noties.markwon.image.AsyncDrawableSpan.draw(AsyncDrawableSpan.java:104)
	at android.text.TextLine.handleReplacement(TextLine.java:940)
	at android.text.TextLine.handleRun(TextLine.java:1040)
	at android.text.TextLine.drawRun(TextLine.java:481)
	at android.text.TextLine.draw(TextLine.java:217)
	at android.text.Layout.drawText(Layout.java:539)
	at android.text.Layout.draw(Layout.java:286)
	at android.widget.TextView.onDraw(TextView.java:7036)
	at android.view.View.draw(View.java:19314)
	at android.view.View.updateDisplayListIfDirty(View.java:18250)
	at android.view.View.draw(View.java:19042)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4271)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4054)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
	at android.view.View.updateDisplayListIfDirty(View.java:18241)

**Comment by noties** [comment]
Hello @huweijian5 ,

can you give me more context about this stacktrace? 

* What markdown did you use? 
* What image loader are you using? 
* How do you initialize your image loader?
* Anything at all related to it?

**Comment by huweijian5** [comment]
What markdown did you use?
4.6.0
What image loader are you using?
glide4.11.0
How do you initialize your image loader?
 .usePlugin(GlideImagesPlugin.create(context))
Anything at all related to it?
it happens occasionally
crash in HuaWei/EMOTION/EmotionUI_8.0.0
i use markwon in RecyclerView

**Comment by noties** [comment]
Hello @huweijian5 ,

can you reproduce this issue on your device? It is possible that the issue is related to this specific device and includes some race condition. But it is hard to confirm without a way to validate any assumptions

**Comment by huweijian5** [comment]
It happened by accident, but it did happen.

**Comment by noties** [comment]
It you happen to have this device, can you have a breakpoint and see on what thread the `at io.noties.markwon.image.AsyncDrawable.initWithKnownDimensions(AsyncDrawable.java:319)` method is called? 

Do you use `AsyncLayoutInflater` or something similar by the way?
