### ISSUE TITLE
How to zoom images on click ?

### ISSUE THREAD

**Issue by damionx7** [noties/Markwon#325]
How can one zoom images on click. As current images are too small to read

![Screenshot_20201221-091151166 (1).jpg](https://user-images.githubusercontent.com/6530843/102737134-99280d80-436c-11eb-9294-b78d897f6852.jpg)

**Comment by damionx7** [comment]
Maybe we can create an intent for gallery on image click ?
 Is that possible ?

**Comment by noties** [comment]
Hello @damionx7 ,

if you want to have all images clickable, then you can use [something like this](https://github.com/noties/Markwon/blob/master/app-sample/src/main/java/io/noties/markwon/app/samples/image/ClickImageSample.kt)

**Comment by damionx7** [comment]
Thanks @noties . One more thing, I now get this when i click on image ? How can I add permission for intent ? 

```
2020-12-21 19:21:29.712 22621-22621/org.eu.thedoc.zettelnotes D/StrictMode: StrictMode policy violation: android.os.strictmode.ContentUriWithoutPermissionViolation: content://com.android.externalstorage.documents/tree/primary%3AShared%2Fmarkor%2Fnotes/document/primary%3AShared%2Fmarkor%2Fnotes%2FIMG_20201218112024.jpg exposed beyond app through Intent.getData() without permission grant flags; did you forget FLAG_GRANT_READ_URI_PERMISSION?
        at android.os.StrictMode.onContentUriWithoutPermission(StrictMode.java:2091)
        at android.net.Uri.checkContentUriWithoutPermission(Uri.java:2407)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10849)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10789)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1712)
        at android.app.Activity.startActivityForResult(Activity.java:5210)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at android.app.Activity.startActivityForResult(Activity.java:5168)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
        at android.app.Activity.startActivity(Activity.java:5539)
        at android.app.Activity.startActivity(Activity.java:5507)
        at io.noties.markwon.LinkResolverDef.resolve(LinkResolverDef.java:26)
        at org.eu.thedoc.zettelnotes.utils.markdown.ImageLinkResolver.resolve(ImageLinkResolver.java:21)
        at io.noties.markwon.core.spans.LinkSpan.onClick(LinkSpan.java:30)
        at me.saket.bettermovementmethod.BetterLinkMovementMethod.dispatchUrlClick(BetterLinkMovementMethod.java:392)
        at me.saket.bettermovementmethod.BetterLinkMovementMethod.onTouchEvent(BetterLinkMovementMethod.java:248)
        at android.widget.TextView.onTouchEvent(TextView.java:10911)
        at android.view.View.dispatchTouchEvent(View.java:13954)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4011)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
    	at android.view.View.dispatchPointerEvent(View.java
```

This is my link resolver class

```
public class ImageLinkResolver implements LinkResolver {

  private final LinkResolver mLinkResolver;

  public ImageLinkResolver(LinkResolver linkResolver) {
    mLinkResolver = linkResolver;
  }

  @Override
  public void resolve(@NonNull View view, @NonNull String link) {
    Timber.v(link);
    mLinkResolver.resolve(view, link);
  }
}
```

**Comment by damionx7** [comment]
I ended up using
```
    if(link.startsWith("content://")){
      Intent intent = new Intent();
      intent.setAction(android.content.Intent.ACTION_VIEW);
      intent.setDataAndType(Uri.parse(link),"image/*");
      intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_GRANT_READ_URI_PERMISSION);
      view.getContext().startActivity(intent);
    }else{
      mLinkResolver.resolve(view, link);
    }
```
