### ISSUE TITLE
Coil latest version? 

### ISSUE THREAD

**Issue by mochadwi** [noties/Markwon#352]
* **Markwon version**: 4.5.1

1. Please specify expected/actual behavior

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcoil/request/LoadRequest;
       at io.noties.markwon.image.coil.CoilImagesPlugin$1.load(CoilImagesPlugin.java:51)
       at io.noties.markwon.image.coil.CoilImagesPlugin$CoilAsyncDrawableLoader.load(CoilImagesPlugin.java:130)
       at io.noties.markwon.image.AsyncDrawable.setCallback2(AsyncDrawable.java:152)
       at io.noties.markwon.image.AsyncDrawableScheduler.schedule(AsyncDrawableScheduler.java:67)
       at io.noties.markwon.image.coil.CoilImagesPlugin.afterSetText(CoilImagesPlugin.java:112)
       at io.noties.markwon.MarkwonImpl.setParsedMarkdown(MarkwonImpl.java:140)
       at io.noties.markwon.MarkwonImpl.setMarkdown(MarkwonImpl.java:113)
```

2. Please specify conditions/steps to reproduce (layout, code, markdown used, etc)

We're using Coil v1.1.1, therefore the Markwon seems using Coil 0.12.0, throwing (class not found clashed with our Coil version)

Cmiiw, is it possible for us to ignore Markwon Coil version and use ours instead? Or should we fork our own Markwon version for temporary? 🙏

**Comment by noties** [comment]
Hello @mochadwi ,

`Coil` support is a community effort and contribution. Right now you can create own version of `CoilImagesPlugin` that uses any version of `Coil` - image loader is [pretty trivial](https://github.com/noties/Markwon/blob/c4cb4420b1dd37ae24d87d4d801f703cd2872141/markwon-image-coil/src/main/java/io/noties/markwon/image/coil/CoilImagesPlugin.java). Of cause community would be very grateful if you can contribute back with changes required 🙌

**Comment by mochadwi** [comment]
Turns out Markwon v4.6.2 already using coil v0.13.0 (including breaking changes of `LoaderRequest` in v0.12.0), thanks for the reply 🎉
