### ISSUE TITLE
Selecting text causes crash

### ISSUE THREAD

**Issue by spectrl** [noties/Markwon#41]
Setting `textIsSelectable=true` and then trying to select some text causes an `IndexOutOfBoundsException`:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
       at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:442)
       at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:163)
       at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:152)
       at android.text.SpannableString.setSpan(SpannableString.java:46)
       at android.text.Selection.setSelection(Selection.java:76)
       at android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState(Editor.java:5613)
       at android.widget.Editor$SelectionModifierCursorController.onTouchEvent(Editor.java:5450)
       at android.widget.Editor.onTouchEvent(Editor.java:1370)
       at android.widget.TextView.onTouchEvent(TextView.java:9657)
       at android.view.View.dispatchTouchEvent(View.java:11776)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
       at android.view.View.dispatchPointerEvent(View.java:12015)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

After a bit of searching it seems like it might be something to do with the `textIsSelectable` property not playing nicely with the `LinkMovementMethod` that is being set.
[https://issuetracker.google.com/issues/37068143](https://issuetracker.google.com/issues/37068143)

I've worked around the issue for now using the answer provided [here](https://stackoverflow.com/questions/22810147/) – extending `MarkwonCompatView` – but it would be good to get a fix in the library.

**Comment by noties** [comment]
Hey @spectrl !

I have checked and this bug is indeed _linked_ with the `LinkMovementMethod`. So I have updated current `snapshot` version (see [here](https://github.com/noties/Markwon/tree/v1.0.6)) to add another method to the `Markwon` class. Now there is a `Markwon.setText(textView, markdown, movementMethod)` one. So, if you do not care about links in your markdown you can pass there `null`. Or, if you do maybe an alternative (such as [Better-Link-Movement-Method](https://github.com/saket/Better-Link-Movement-Method) would be a better fit; I did check `textIsSelectable` with it on `6.0.0` and it works as expected)

**Comment by doctorfox** [comment]
> 
> 
> Also, I have found (at least in an emulator with API level 16), that using `textIsSelectable=true` causes immediate crash. Meanwhile using:
> 
> ```java
> textView.setText(text);
> textView.post(() -> textView.setTextIsSelectable(true));
> ```
> 
> does not. I do not know if it's an emulator issue or not, but still FYI

This worked perfectly:

```
textView.post(new Runnable() {
            @Override
            public void run() {
                textView.setTextIsSelectable(true);
            }
        });
```

**Comment by VyacheslavDev** [comment]
thanks, your solution works good
